"""
ConversationStore — filesystem-backed persistence for restorable chat history.

Each record captures one conversation so it can be relisted in the sidebar
「最近」list and fully restored later:

  - `messages`        : the Anthropic-format message list of the WebSession,
                        so the agent's context is reinstated and the user can
                        keep chatting from where they left off.
  - `chat_html` /
    `dashboard_html`  : the client-rendered chat + dashboard DOM at save time,
                        so the transcript and its cards re-appear exactly
                        (re-deriving the rich cards from `messages` alone is not
                        possible — chart/table specs are stripped before they
                        reach the model).

One conversation == one JSON file under `<cwd>/dataset/conversations/`. The active
conversation's id is owned by the browser (per mode) and passed back on each
save so a growing conversation updates its record in place instead of spawning
duplicates.

The directory also contains a small ``history_index.json``.  It is deliberately
separate from the full snapshots: the sidebar can read titles and timestamps
without opening every conversation.  Older installations do not have the
index, so the first list call performs a one-time compatibility scan and writes
it for subsequent calls.
"""

from __future__ import annotations

import json
import os
import secrets
import re
import tempfile
import hashlib
import threading
from html.parser import HTMLParser
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from ..paths import CONVERSATIONS_DIR, project_path

try:
    from zoneinfo import ZoneInfo
except ImportError:  # pragma: no cover - Python 3.10+ includes zoneinfo
    ZoneInfo = None  # type: ignore[assignment,misc]


TITLE_ALGORITHM_VERSION = 3
HISTORY_INDEX_VERSION = 3
MAX_CONVERSATIONS = 100          # keep newest N per store; prune the rest
MAX_HTML_BYTES = 4_000_000       # per-blob safety cap (~4 MB)
VALID_MODES = ("data", "report")
CID_RE = re.compile(r"^[0-9a-f]{8,64}$", re.IGNORECASE)
SOURCE_CONFIG_KEYS = (
    "ontology",
    "database",
    "retrieval_mode",
    "graph",
    "doris_api_url",
    "doris_jdbc_url",
    "doris_driver",
    "doris_username",
    "doris_database",
)

# These are generated by the agent/runtime rather than typed by the user.
# They can appear as role=user messages in the Anthropic protocol, so title
# extraction must explicitly ignore them when reading legacy snapshots.
_INTERNAL_USER_PREFIXES = (
    "⚠️",
    "本轮回复已经出现",
    "本轮回复",
    "本轮分析",
    "渲染规则提醒",
    "强制纪律检查",
    "现在立刻补做",
)


def sanitize_source_config(config: Optional[dict[str, Any]]) -> dict[str, str]:
    """Keep only non-secret source metadata suitable for history snapshots.

    The browser sends this object back when saving a conversation and an old
    record may have been written before the current whitelist existed.  The
    filter therefore belongs at the persistence boundary, not only in the
    current frontend implementation.  In particular, credentials such as
    ``doris_password`` must never reach a history file, sync payload, or
    restore response.
    """
    if not isinstance(config, dict):
        return {}
    safe: dict[str, str] = {}
    for key in SOURCE_CONFIG_KEYS:
        value = config.get(key)
        if value is None:
            continue
        text = str(value).strip()
        if text:
            safe[key] = text[:1000]
    return safe


def _text_content(content: Any) -> str:
    """Extract only human-readable text blocks from a message payload."""
    if isinstance(content, str):
        return content
    if isinstance(content, dict):
        if content.get("type") in {"tool_result", "tool_use"}:
            return ""
        text = content.get("text")
        return text if isinstance(text, str) else ""
    if not isinstance(content, list):
        return ""
    parts: list[str] = []
    for item in content:
        if isinstance(item, str):
            parts.append(item)
            continue
        if not isinstance(item, dict) or item.get("type") in {"tool_result", "tool_use"}:
            continue
        text = item.get("text")
        if isinstance(text, str):
            parts.append(text)
    return " ".join(parts)


def first_user_question(messages: list[Any]) -> str:
    """Return the first real user question, normalized for a history title.

    The returned value is empty when a snapshot contains no real user input;
    callers should use :func:`conversation_title` when they need the fallback.
    """
    for message in messages or []:
        if not isinstance(message, dict) or message.get("role") != "user":
            continue
        if (message.get("internal") or message.get("is_internal") or
                message.get("hidden") or message.get("is_hidden")):
            continue
        if message.get("metadata", {}).get("internal") if isinstance(message.get("metadata"), dict) else False:
            continue
        text = re.sub(r"\s+", " ", _text_content(message.get("content"))).strip()
        if not text or text.startswith(_INTERNAL_USER_PREFIXES):
            continue
        return text[:60]
    return ""


def conversation_title(messages: list[Any]) -> str:
    """Return the only authoritative title for a conversation snapshot."""
    return first_user_question(messages) or "未命名对话"


class _FirstVisibleUserParser(HTMLParser):
    """Extract text from the first visible ``.msg-user .msg-body`` node."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.user_depth = 0
        self.body_depth = 0
        self.skip_depth = 0
        self.parts: list[str] = []
        self.found = False

    @staticmethod
    def _classes(attrs: list[tuple[str, Optional[str]]]) -> set[str]:
        return set(str(dict(attrs).get("class") or "").split())

    def handle_starttag(self, tag: str, attrs: list[tuple[str, Optional[str]]]) -> None:
        classes = self._classes(attrs)
        if self.found:
            return
        if not self.user_depth and "msg-user" in classes:
            self.user_depth = 1
        elif self.user_depth:
            self.user_depth += 1
        if self.user_depth and "msg-body" in classes and not self.body_depth:
            self.body_depth = self.user_depth
        if self.skip_depth:
            self.skip_depth += 1
        elif self.body_depth and ("antd-message-host" in classes or "thinking-step" in classes):
            self.skip_depth = 1

    def handle_endtag(self, tag: str) -> None:
        if self.skip_depth:
            self.skip_depth -= 1
        if self.user_depth:
            if self.body_depth == self.user_depth:
                self.body_depth = 0
            self.user_depth -= 1
            if self.user_depth == 0:
                self.found = True

    def handle_data(self, data: str) -> None:
        if self.body_depth and not self.skip_depth:
            self.parts.append(data)


def first_visible_user_question(chat_html: Any) -> str:
    if not chat_html:
        return ""
    parser = _FirstVisibleUserParser()
    try:
        parser.feed(str(chat_html))
        parser.close()
    except Exception:
        return ""
    text = re.sub(r"\s+", " ", " ".join(parser.parts)).strip()
    if not text or text.startswith(_INTERNAL_USER_PREFIXES):
        return ""
    return text[:60]


def record_first_user_question(record: dict[str, Any], override: str = "") -> str:
    """Return the first visible question, with legacy-source fallbacks."""
    explicit = re.sub(r"\s+", " ", str(override or "")).strip()[:60]
    if explicit and not explicit.startswith(_INTERNAL_USER_PREFIXES):
        return explicit
    visible = first_visible_user_question(record.get("chat_html"))
    if visible:
        return visible
    stored = record.get("first_user_question")
    if isinstance(stored, str):
        stored = re.sub(r"\s+", " ", stored).strip()[:60]
        if stored and not stored.startswith(_INTERNAL_USER_PREFIXES):
            return stored
    messages = record.get("messages") if isinstance(record.get("messages"), list) else []
    return first_user_question(messages)


def record_title(record: dict[str, Any]) -> str:
    return record_first_user_question(record) or "未命名对话"


def _now_iso() -> str:
    # Persist a stable business timezone instead of depending on the host's
    # local timezone (which differs between a developer laptop and Docker).
    if ZoneInfo is not None:
        return datetime.now(ZoneInfo("Asia/Shanghai")).isoformat(timespec="seconds")
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


class ConversationStore:
    """Filesystem-backed conversation store. One instance per app."""

    def __init__(self, cwd: str) -> None:
        self.root = project_path(cwd, CONVERSATIONS_DIR)
        self.root.mkdir(parents=True, exist_ok=True)
        # FastAPI may execute synchronous handlers concurrently. Serialize
        # snapshot + index updates so two first saves cannot create divergent
        # index states or overwrite one another's metadata.
        self._lock = threading.RLock()
        # Repair legacy titles once when the store is opened. Subsequent list
        # calls use the lightweight index and do not rescan full snapshots.
        self.last_title_migrations = self.migrate_titles()
        self.last_unresolved_title_migrations = getattr(self, "last_unresolved_title_migrations", 0)
        self.last_title_migration_scanned = getattr(self, "last_title_migration_scanned", 0)
        self.last_index_rebuild_count = len(self._index())

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------
    def _path(self, cid: str) -> Path:
        # IDs are generated by token_hex and must stay a single safe filename.
        # Reject malformed IDs instead of silently mapping them to `.json` or
        # collapsing distinct user input into the same file.
        safe = str(cid or "").strip()
        if not CID_RE.fullmatch(safe):
            raise ValueError("invalid conversation id")
        return self.root / f"{safe}.json"

    def _index_path(self) -> Path:
        return self.root / "history_index.json"

    def _read_index(self) -> dict[str, dict[str, Any]]:
        try:
            payload = json.loads(self._index_path().read_text(encoding="utf-8"))
            if (not isinstance(payload, dict) or
                    payload.get("version") != HISTORY_INDEX_VERSION or
                    payload.get("title_version") != TITLE_ALGORITHM_VERSION):
                return {}
            entries = payload.get("conversations") if isinstance(payload, dict) else None
            if not isinstance(entries, dict):
                return {}
            return {
                str(cid): value
                for cid, value in entries.items()
                if CID_RE.fullmatch(str(cid)) and isinstance(value, dict)
            }
        except Exception:
            return {}

    def _write_index(self, entries: dict[str, dict[str, Any]]) -> None:
        """Atomically persist only the fields needed by the history list."""
        payload = json.dumps(
            {"version": HISTORY_INDEX_VERSION, "title_version": TITLE_ALGORITHM_VERSION, "conversations": entries},
            ensure_ascii=False,
        )
        temp_path: Optional[str] = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", encoding="utf-8", dir=self.root,
                prefix=".history_index.", suffix=".tmp", delete=False,
            ) as tmp:
                temp_path = tmp.name
                tmp.write(payload)
                tmp.flush()
                os.fsync(tmp.fileno())
            os.replace(temp_path, self._index_path())
            temp_path = None
        finally:
            if temp_path:
                try:
                    os.unlink(temp_path)
                except OSError:
                    pass

    def _load(self, cid: str) -> Optional[dict[str, Any]]:
        try:
            p = self._path(cid)
        except ValueError:
            return None
        if not p.exists():
            return None
        try:
            rec = json.loads(p.read_text(encoding="utf-8"))
            if not isinstance(rec, dict) or str(rec.get("id") or "").lower() != str(cid).lower():
                return None
            # Sanitize on read as well as on write so legacy records cannot
            # leak a credential through restore or the internal sync endpoint.
            rec["source_config"] = sanitize_source_config(rec.get("source_config"))
            return rec
        except Exception:
            return None

    @staticmethod
    def _first_question_title(messages: list[Any]) -> str:
        """Back-compatible alias for the canonical title source."""
        return first_user_question(messages)

    @staticmethod
    def _content_text(content: Any) -> str:
        return re.sub(r"\s+", " ", _text_content(content)).strip()

    @classmethod
    def _turn_count(cls, messages: list[Any]) -> int:
        """Count user turns, excluding tool-result protocol messages."""
        count = 0
        for message in messages or []:
            if not isinstance(message, dict) or message.get("role") != "user":
                continue
            if cls._content_text(message.get("content")):
                count += 1
        return count

    @classmethod
    def _preview(cls, messages: list[Any]) -> list[dict[str, str]]:
        """Return a bounded plain-text transcript for the preview endpoint."""
        result: list[dict[str, str]] = []
        for message in messages or []:
            if not isinstance(message, dict) or message.get("role") not in {"user", "assistant"}:
                continue
            text = cls._content_text(message.get("content"))
            if not text:
                continue
            result.append({
                "role": str(message.get("role")),
                "text": text[:600],
            })
            if len(result) >= 16:
                break
        return result

    @classmethod
    def _metadata(cls, rec: dict[str, Any]) -> dict[str, Any]:
        messages = rec.get("messages") if isinstance(rec.get("messages"), list) else []
        first_question = record_first_user_question(rec)
        title = first_question or "未命名对话"
        turn_count = rec.get("turn_count")
        if not isinstance(turn_count, int):
            turn_count = cls._turn_count(messages)
        preview = rec.get("preview")
        if not isinstance(preview, list):
            preview = cls._preview(messages)
        return {
            "id": rec.get("id"),
            "mode": rec.get("mode") if rec.get("mode") in VALID_MODES else "data",
            "title": title or "未命名对话",
            "first_user_question": first_question,
            "updated_at": rec.get("updated_at") or "",
            "created_at": rec.get("created_at") or rec.get("updated_at") or "",
            "turn_count": turn_count,
            "message_count": len(messages),
            "schema_version": int(rec.get("schema_version") or 1),
            "title_version": int(rec.get("title_version") or 1),
            "preview": preview,
            "source_config_present": bool(sanitize_source_config(rec.get("source_config"))),
            "has_ontology_html": bool(str(rec.get("ontology_html") or "").strip()),
        }

    def _record_paths(self) -> list[Path]:
        return [p for p in self.root.glob("*.json") if p.name != self._index_path().name]

    def _rebuild_index(self) -> dict[str, dict[str, Any]]:
        entries: dict[str, dict[str, Any]] = {}
        for path in self._record_paths():
            try:
                rec = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            cid = str(rec.get("id") or "") if isinstance(rec, dict) else ""
            if not isinstance(rec, dict) or not CID_RE.fullmatch(cid):
                continue
            if rec.get("duplicate_of"):
                continue
            entries[cid] = self._metadata(rec)
        self._write_index(entries)
        return entries

    def _index(self) -> dict[str, dict[str, Any]]:
        entries = self._read_index()
        actual_ids: set[str] = set()
        for path in self._record_paths():
            if not CID_RE.fullmatch(path.stem):
                continue
            try:
                raw = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            if isinstance(raw, dict) and not raw.get("duplicate_of"):
                actual_ids.add(path.stem)
        # A missing index, a malformed index, or a record copied in from an
        # older installation triggers one compatibility scan. Normal reads
        # only parse this small metadata file.
        if set(entries) != actual_ids:
            entries = self._rebuild_index()
        return entries

    def migrate_titles(self) -> int:
        """Canonicalize legacy record/index titles without touching content.

        The JSON snapshots are rewritten atomically only when their ``title``
        differs. All other fields are loaded and serialized unchanged. The
        index is regenerated from the same metadata function, making this
        operation safe and idempotent.
        """
        entries: dict[str, dict[str, Any]] = {}
        changed = 0
        unresolved = 0
        scanned = 0
        for path in self._record_paths():
            try:
                rec = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            cid = str(rec.get("id") or "") if isinstance(rec, dict) else ""
            if not isinstance(rec, dict) or not CID_RE.fullmatch(cid):
                continue
            scanned += 1
            first_question = record_first_user_question(rec)
            if not first_question and rec.get("chat_html"):
                first_question = self._first_question_from_chat_html(rec.get("chat_html"))
            if not first_question:
                unresolved += 1
            canonical = first_question or "未命名对话"
            if (rec.get("title") != canonical or
                    rec.get("first_user_question") != first_question or
                    rec.get("title_version") != TITLE_ALGORITHM_VERSION):
                rec["title"] = canonical
                rec["first_user_question"] = first_question
                rec["title_version"] = TITLE_ALGORITHM_VERSION
                payload = json.dumps(rec, ensure_ascii=False)
                temp_path: Optional[str] = None
                try:
                    with tempfile.NamedTemporaryFile(
                        mode="w", encoding="utf-8", dir=self.root,
                        prefix=f".{cid}.title.", suffix=".tmp", delete=False,
                    ) as tmp:
                        temp_path = tmp.name
                        tmp.write(payload)
                        tmp.flush()
                        os.fsync(tmp.fileno())
                    os.replace(temp_path, path)
                    temp_path = None
                finally:
                    if temp_path:
                        try:
                            os.unlink(temp_path)
                        except OSError:
                            pass
                changed += 1
            if not rec.get("duplicate_of"):
                entries[cid] = self._metadata(rec)
        self.last_unresolved_title_migrations = unresolved
        self.last_title_migration_scanned = scanned
        if entries != self._read_index():
            self._write_index(entries)
        return changed

    @staticmethod
    def _first_question_from_chat_html(chat_html: Any) -> str:
        from html import unescape
        text = str(chat_html or "")
        match = re.search(r'<[^>]*class=["\'][^"\']*msg-user[^"\']*["\'][^>]*>(.*?)</[^>]+>', text, re.I | re.S)
        if not match:
            return ""
        plain = re.sub(r"<[^>]+>", " ", match.group(1))
        return re.sub(r"\s+", " ", unescape(plain)).strip()[:60]

    @staticmethod
    def _summary(rec: dict[str, Any]) -> dict[str, Any]:
        return {
            "id": rec.get("id"),
            "mode": rec.get("mode"),
            "title": rec.get("title"),
            "first_user_question": rec.get("first_user_question") or "",
            "updated_at": rec.get("updated_at"),
            "created_at": rec.get("created_at"),
            "turn_count": rec.get("turn_count", 0),
            "message_count": rec.get("message_count", 0),
            "schema_version": rec.get("schema_version", 1),
            "title_version": rec.get("title_version", TITLE_ALGORITHM_VERSION),
        }

    def _prune(self) -> None:
        entries = self._index()
        ordered = sorted(entries.items(), key=lambda item: (
            item[1].get("updated_at") or "", item[0]
        ), reverse=True)
        for cid, _ in ordered[MAX_CONVERSATIONS:]:
            try:
                self._path(cid).unlink(missing_ok=True)
            except Exception:
                pass
            entries.pop(cid, None)
        self._write_index(entries)

    def _new_id(self) -> str:
        """Return an unused id even when the random generator collides.

        Eight hex characters are sufficient for normal use, but a collision
        must never overwrite another conversation (tests, restored backups,
        and long-lived installations can all make that possible).
        """
        for _ in range(16):
            cid = secrets.token_hex(4)
            if not self._path(cid).exists():
                return cid
        raise RuntimeError("无法生成唯一会话 ID")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def save(self, **kwargs: Any) -> dict[str, Any]:
        """Serialize a save for this process and return the local summary."""
        with self._lock:
            return self._save_unlocked(**kwargs)

    def _save_unlocked(
        self,
        *,
        mode: str,
        title: str,
        messages: list,
        chat_html: str,
        dashboard_html: str,
        ontology_html: str = "",
        tools_html: str = "",
        llm_html: str = "",
        sop_steps: Optional[list[dict[str, Any]]] = None,
        source_config: Optional[dict[str, Any]] = None,
        cid: Optional[str] = None,
        first_user_question_override: str = "",
    ) -> dict[str, Any]:
        """Create or update (when `cid` exists) a conversation record."""
        if mode not in VALID_MODES:
            mode = "data"
        created = None
        existing_source_config: Optional[dict[str, Any]] = None
        existing_first_user_question = ""
        if cid:
            existing = self._load(cid)
            if existing and not existing.get("duplicate_of") and existing.get("mode") == mode:
                created = existing.get("created_at")
                if isinstance(existing.get("source_config"), dict):
                    existing_source_config = existing.get("source_config")
                existing_first_user_question = record_first_user_question(existing)
            elif existing:
                # Never mutate a record from the other mode or a migrated
                # duplicate into the current mode's conversation.
                cid = None
            else:
                # A valid client draft id is a reservation, not a reason to
                # mint another id. This makes two concurrent first saves
                # converge on one physical record. Invalid ids still fall
                # back to a server-generated id.
                try:
                    self._path(cid)
                except ValueError:
                    cid = None
        if not cid:
            cid = self._new_id()
        now = _now_iso()
        raw_source_config = (
            source_config if source_config is not None else existing_source_config
        )
        rec = {
            "id": cid,
            "schema_version": 2,
            "title_version": TITLE_ALGORITHM_VERSION,
            "mode": mode,
            # `title` remains in the API for compatibility, but is never
            # trusted. The first real user question is the sole authority.
            "first_user_question": (
                first_user_question_override
                or first_visible_user_question(chat_html)
                or first_user_question(messages or [])
                or existing_first_user_question
            ),
            "title": (
                first_user_question_override
                or first_visible_user_question(chat_html)
                or first_user_question(messages or [])
                or existing_first_user_question
                or "未命名对话"
            ),
            "created_at": created or now,
            "updated_at": now,
            "messages": messages or [],
            "message_count": len(messages or []),
            "turn_count": self._turn_count(messages or []),
            "preview": self._preview(messages or []),
            "chat_html": (chat_html or "")[:MAX_HTML_BYTES],
            "dashboard_html": (dashboard_html or "")[:MAX_HTML_BYTES],
            "ontology_html": (ontology_html or "")[:MAX_HTML_BYTES],
            "tools_html": (tools_html or "")[:MAX_HTML_BYTES],
            "llm_html": (llm_html or "")[:MAX_HTML_BYTES],
            # The SOP is part of the conversation snapshot rather than a
            # process-global UI state. Keep only the small, normalized list
            # supplied by the browser; old records simply omit this field.
            "sop_steps": [
                {
                    "content": str(item.get("content") or "")[:200],
                    "status": str(item.get("status") or "pending"),
                }
                for item in (sop_steps or [])
                if isinstance(item, dict)
            ][:32],
            # Source selection is part of the conversation context. Keep only
            # non-secret values: credentials must remain process/environment
            # state and must never be copied into history JSON or sync payloads.
            "source_config": sanitize_source_config(raw_source_config),
        }
        target = self._path(cid)
        payload = json.dumps(rec, ensure_ascii=False)
        # Replace the snapshot atomically. A browser save and a server-side
        # sync can overlap; never leave a partially-written JSON document for
        # the history list to read.
        temp_path: Optional[str] = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", encoding="utf-8", dir=self.root, prefix=f".{cid}.",
                suffix=".tmp", delete=False
            ) as tmp:
                temp_path = tmp.name
                tmp.write(payload)
                tmp.flush()
                os.fsync(tmp.fileno())
            os.replace(temp_path, target)
            temp_path = None
        finally:
            if temp_path:
                try:
                    os.unlink(temp_path)
                except OSError:
                    pass
        self._prune()
        entries = self._index()
        entries[str(cid)] = self._metadata(rec)
        self._write_index(entries)
        return self._summary(entries[str(cid)])

    def list(self, mode: Optional[str] = None) -> list[dict[str, Any]]:
        """Return conversation summaries, newest first, optionally by mode."""
        out: list[dict[str, Any]] = []
        for metadata in self._index().values():
            if mode and metadata.get("mode") != mode:
                continue
            out.append(self._summary(metadata))
        out.sort(key=lambda r: (r.get("updated_at") or "", r.get("id") or ""), reverse=True)
        return out

    def get(self, cid: str) -> Optional[dict[str, Any]]:
        rec = self._load(cid)
        if rec:
            rec["first_user_question"] = record_first_user_question(rec)
            rec["title"] = record_title(rec)
        return rec

    def update_ontology_html(self, cid: str, ontology_html: str) -> bool:
        """Update only the rendered ontology snapshot during history migration.

        This deliberately keeps ``updated_at`` unchanged: opening an old
        conversation must not move it to the top of the recent list.
        """
        rec = self._load(cid)
        if not rec:
            return False
        value = (ontology_html or "")[:MAX_HTML_BYTES]
        if rec.get("ontology_html") == value:
            return True
        rec["ontology_html"] = value
        payload = json.dumps(rec, ensure_ascii=False)
        temp_path: Optional[str] = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", encoding="utf-8", dir=self.root, prefix=f".{cid}.",
                suffix=".tmp", delete=False
            ) as tmp:
                temp_path = tmp.name
                tmp.write(payload)
                tmp.flush()
                os.fsync(tmp.fileno())
            os.replace(temp_path, self._path(cid))
            temp_path = None
        finally:
            if temp_path:
                try:
                    os.unlink(temp_path)
                except OSError:
                    pass
        entries = self._index()
        if str(cid) in entries:
            entries[str(cid)] = self._metadata(rec)
            self._write_index(entries)
        return True

    def delete(self, cid: str) -> bool:
        try:
            p = self._path(cid)
        except ValueError:
            return False
        if p.exists():
            try:
                p.unlink()
                entries = self._read_index()
                entries.pop(str(cid), None)
                self._write_index(entries)
                return True
            except Exception:
                return False
        return False

    def diagnose(self) -> list[dict[str, Any]]:
        """Return a read-only integrity report for every physical snapshot."""
        report: list[dict[str, Any]] = []
        groups: dict[tuple[str, str], list[str]] = {}
        records: dict[str, dict[str, Any]] = {}
        for path in self._record_paths():
            try:
                rec = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            if not isinstance(rec, dict):
                continue
            cid = str(rec.get("id") or path.stem)
            messages = rec.get("messages") if isinstance(rec.get("messages"), list) else []
            digest = hashlib.sha256(json.dumps(messages, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
            mode = rec.get("mode") if rec.get("mode") in VALID_MODES else "data"
            groups.setdefault((mode, digest), []).append(cid)
            records[cid] = rec
        duplicate_ids = {cid for ids in groups.values() if len(ids) > 1 for cid in ids}
        for cid, rec in records.items():
            messages = rec.get("messages") if isinstance(rec.get("messages"), list) else []
            mode = rec.get("mode") if rec.get("mode") in VALID_MODES else "data"
            digest = hashlib.sha256(json.dumps(messages, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
            canonical = conversation_title(messages)
            report.append({
                "id": cid, "mode": mode,
                "created_at": rec.get("created_at") or "",
                "updated_at": rec.get("updated_at") or "",
                "title": rec.get("title") or "",
                "canonical_title": canonical,
                "message_count": len(messages),
                "title_mismatch": (rec.get("title") or "") != canonical,
                "suspected_duplicate": cid in duplicate_ids,
                "content_hash": digest,
            })
        return sorted(report, key=lambda x: (x["mode"], x["updated_at"], x["id"]), reverse=True)

    def migrate_exact_duplicates(self) -> list[dict[str, str]]:
        """Mark only byte-equivalent message snapshots as duplicates.

        The old JSON remains addressable; list/index hide the duplicate and
        retain an explicit mapping via ``duplicate_of``.
        """
        with self._lock:
            groups: dict[tuple[str, str], list[dict[str, Any]]] = {}
            for path in self._record_paths():
                try:
                    rec = json.loads(path.read_text(encoding="utf-8"))
                except Exception:
                    continue
                if not isinstance(rec, dict) or rec.get("duplicate_of"):
                    continue
                messages = rec.get("messages") if isinstance(rec.get("messages"), list) else []
                digest = hashlib.sha256(json.dumps(messages, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
                mode = rec.get("mode") if rec.get("mode") in VALID_MODES else "data"
                groups.setdefault((mode, digest), []).append(rec)
            mappings: list[dict[str, str]] = []
            for records in groups.values():
                if len(records) < 2:
                    continue
                def score(rec: dict[str, Any]) -> tuple[int, str, str]:
                    html_size = sum(len(str(rec.get(k) or "")) for k in ("chat_html", "dashboard_html", "ontology_html", "tools_html", "llm_html"))
                    return (html_size + len(rec.get("messages") or []), str(rec.get("updated_at") or ""), str(rec.get("id") or ""))
                keeper = max(records, key=score)
                for rec in records:
                    if rec is keeper:
                        continue
                    rec["duplicate_of"] = str(keeper.get("id"))
                    path = self._path(str(rec.get("id")))
                    temp_path = None
                    try:
                        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=self.root, prefix=f".{path.stem}.duplicate.", suffix=".tmp", delete=False) as tmp:
                            temp_path = tmp.name
                            json.dump(rec, tmp, ensure_ascii=False)
                            tmp.flush(); os.fsync(tmp.fileno())
                        os.replace(temp_path, path); temp_path = None
                    finally:
                        if temp_path:
                            try: os.unlink(temp_path)
                            except OSError: pass
                    mappings.append({"duplicate_id": str(rec.get("id")), "duplicate_of": str(keeper.get("id"))})
            self._rebuild_index()
            return mappings
