"""
ConversationStore — filesystem-backed persistence for restorable chat history.

Each record captures one conversation so it can be relisted in the sidebar
「最近」list and fully restored later:

  - `messages`        : the Anthropic-format message list of the WebSession,
                        so the agent's context is reinstated and the user can
                        keep chatting from where they left off.
  - `chat_html` /
    `dashboard_html`  : the client-rendered chat + dashboard DOM at save time,
                        so the transcript and its cards re-appear exactly
                        (re-deriving the rich cards from `messages` alone is not
                        possible — chart/table specs are stripped before they
                        reach the model).

One conversation == one JSON file under `<cwd>/bi_conversations/`. The active
conversation's id is owned by the browser (per mode) and passed back on each
save so a growing conversation updates its record in place instead of spawning
duplicates.
"""

from __future__ import annotations

import json
import os
import secrets
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

try:
    from zoneinfo import ZoneInfo
except ImportError:  # pragma: no cover - Python 3.10+ includes zoneinfo
    ZoneInfo = None  # type: ignore[assignment,misc]


STORE_DIRNAME = "bi_conversations"
MAX_CONVERSATIONS = 100          # keep newest N per store; prune the rest
MAX_HTML_BYTES = 4_000_000       # per-blob safety cap (~4 MB)
VALID_MODES = ("data", "report")
CID_RE = re.compile(r"^[0-9a-f]{8,64}$", re.IGNORECASE)


def _now_iso() -> str:
    # Persist a stable business timezone instead of depending on the host's
    # local timezone (which differs between a developer laptop and Docker).
    if ZoneInfo is not None:
        return datetime.now(ZoneInfo("Asia/Shanghai")).isoformat(timespec="seconds")
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


class ConversationStore:
    """Filesystem-backed conversation store. One instance per app."""

    def __init__(self, cwd: str) -> None:
        self.root = Path(cwd) / STORE_DIRNAME
        self.root.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------
    def _path(self, cid: str) -> Path:
        # IDs are generated by token_hex and must stay a single safe filename.
        # Reject malformed IDs instead of silently mapping them to `.json` or
        # collapsing distinct user input into the same file.
        safe = str(cid or "").strip()
        if not CID_RE.fullmatch(safe):
            raise ValueError("invalid conversation id")
        return self.root / f"{safe}.json"

    def _load(self, cid: str) -> Optional[dict[str, Any]]:
        try:
            p = self._path(cid)
        except ValueError:
            return None
        if not p.exists():
            return None
        try:
            rec = json.loads(p.read_text(encoding="utf-8"))
            if not isinstance(rec, dict) or str(rec.get("id") or "").lower() != str(cid).lower():
                return None
            return rec
        except Exception:
            return None

    @staticmethod
    def _first_question_title(messages: list[Any]) -> str:
        """Return the stable title source: the first user question."""
        for message in messages or []:
            if not isinstance(message, dict) or message.get("role") != "user":
                continue
            content = message.get("content")
            if isinstance(content, str):
                text = content.strip()
            elif isinstance(content, list):
                text = " ".join(
                    str(item.get("text") or "").strip()
                    for item in content
                    if isinstance(item, dict) and item.get("text")
                ).strip()
            else:
                text = ""
            if text:
                return text.splitlines()[0].strip()[:80]
        return ""

    @staticmethod
    def _summary(rec: dict[str, Any]) -> dict[str, Any]:
        return {
            "id": rec.get("id"),
            "mode": rec.get("mode"),
            "title": rec.get("title"),
            "updated_at": rec.get("updated_at"),
            "created_at": rec.get("created_at"),
        }

    def _prune(self) -> None:
        recs = []
        for p in self.root.glob("*.json"):
            try:
                rec = json.loads(p.read_text(encoding="utf-8"))
            except Exception:
                continue
            if not isinstance(rec, dict) or not CID_RE.fullmatch(str(rec.get("id") or "")):
                continue
            recs.append((p, rec.get("updated_at", "")))
        recs.sort(key=lambda t: t[1], reverse=True)
        for p, _ in recs[MAX_CONVERSATIONS:]:
            try:
                p.unlink(missing_ok=True)
            except Exception:
                pass

    def _new_id(self) -> str:
        """Return an unused id even when the random generator collides.

        Eight hex characters are sufficient for normal use, but a collision
        must never overwrite another conversation (tests, restored backups,
        and long-lived installations can all make that possible).
        """
        for _ in range(16):
            cid = secrets.token_hex(4)
            if not self._path(cid).exists():
                return cid
        raise RuntimeError("无法生成唯一会话 ID")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def save(
        self,
        *,
        mode: str,
        title: str,
        messages: list,
        chat_html: str,
        dashboard_html: str,
        ontology_html: str = "",
        tools_html: str = "",
        llm_html: str = "",
        cid: Optional[str] = None,
    ) -> dict[str, Any]:
        """Create or update (when `cid` exists) a conversation record."""
        if mode not in VALID_MODES:
            mode = "data"
        created = None
        existing_title = None
        if cid:
            existing = self._load(cid)
            if existing:
                created = existing.get("created_at")
                existing_title = self._first_question_title(existing.get("messages") or []) or existing.get("title")
            else:
                cid = None  # stale id — start a fresh record
        if not cid:
            cid = self._new_id()
        now = _now_iso()
        rec = {
            "id": cid,
            "mode": mode,
            # A conversation title is immutable: it is the first question's
            # short title and must not change when later turns are appended.
            "title": (existing_title or title or "未命名对话").strip()[:80] or "未命名对话",
            "created_at": created or now,
            "updated_at": now,
            "messages": messages or [],
            "chat_html": (chat_html or "")[:MAX_HTML_BYTES],
            "dashboard_html": (dashboard_html or "")[:MAX_HTML_BYTES],
            "ontology_html": (ontology_html or "")[:MAX_HTML_BYTES],
            "tools_html": (tools_html or "")[:MAX_HTML_BYTES],
            "llm_html": (llm_html or "")[:MAX_HTML_BYTES],
        }
        target = self._path(cid)
        payload = json.dumps(rec, ensure_ascii=False)
        # Replace the snapshot atomically. A browser save and a server-side
        # sync can overlap; never leave a partially-written JSON document for
        # the history list to read.
        temp_path: Optional[str] = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", encoding="utf-8", dir=self.root, prefix=f".{cid}.",
                suffix=".tmp", delete=False
            ) as tmp:
                temp_path = tmp.name
                tmp.write(payload)
                tmp.flush()
                os.fsync(tmp.fileno())
            os.replace(temp_path, target)
            temp_path = None
        finally:
            if temp_path:
                try:
                    os.unlink(temp_path)
                except OSError:
                    pass
        self._prune()
        return self._summary(rec)

    def list(self, mode: Optional[str] = None) -> list[dict[str, Any]]:
        """Return conversation summaries, newest first, optionally by mode."""
        out: list[dict[str, Any]] = []
        for p in self.root.glob("*.json"):
            try:
                rec = json.loads(p.read_text(encoding="utf-8"))
            except Exception:
                continue
            if not isinstance(rec, dict) or not CID_RE.fullmatch(str(rec.get("id") or "")):
                continue
            if mode and rec.get("mode") != mode:
                continue
            first_title = self._first_question_title(rec.get("messages") or [])
            if first_title:
                rec["title"] = first_title
            out.append(self._summary(rec))
        out.sort(key=lambda r: r.get("updated_at") or "", reverse=True)
        return out

    def get(self, cid: str) -> Optional[dict[str, Any]]:
        rec = self._load(cid)
        if rec:
            first_title = self._first_question_title(rec.get("messages") or [])
            if first_title:
                rec["title"] = first_title
        return rec

    def delete(self, cid: str) -> bool:
        try:
            p = self._path(cid)
        except ValueError:
            return False
        if p.exists():
            try:
                p.unlink()
                return True
            except Exception:
                return False
        return False
